// defining the colors we might use in our program
#define BLACK     "\x1B[30m"
#define RED       "\x1B[31m"
#define GREEN     "\x1b[92m"
#define YELLOW    "\x1b[43m"
#define BLUE      "\x1B[34m"
#define MAGENTA   "\x1B[35m"
#define CYAN      "\x1B[36m"
#define WHITE     "\x1B[37m"
#define RESET     "\x1B[0m"